 SELECT DISTINCT ?term ?concept ?prefLabel WHERE  {
     ?concept skos:prefLabel ?term .
     ?concept skos:inScheme ?conceptScheme .
     FILTER(regex(str(?conceptScheme),'mineralConcColourValueCode'))
     ?concept skos:prefLabel ?prefLabel .
 }
 ORDER BY ?term
